### ISSUE TITLE
Example links are broken

### ISSUE THREAD

**Issue by zhedar** [TheCoder4eu/BootsFacesWeb#17]
As the examples have been moved to another repository, the links to them no longer work both in the current snapshot locally and in the [live version](http://showcase.bootsfaces.net/Examples/starter_template.jsf) (see View Page Source), this applies for the other examples as well.
The showcase also seems to be a bit out of sync with this repo, so fixing it directly via a PR isn't possible at the moment.

**Comment by stephanrauh** [comment]
The URL of the develoment showcase is www3.bootsfaces.net/Showcase/. Each time we push something to the repository, a new copy of the showcase application is built and deployed. The main branch of the showcase is updated when we publish a new release.

**Comment by zhedar** [comment]
That's quite nice to know, but what about http://www3.bootsfaces.net/Examples/ ? It looks like it is running as another deployed application, but does that actually exists as a repo? [This one](https://github.com/stephanrauh/BootsFaces-Examples) doesn't seem to be it. Because that's actually the one where the broken links are in.

**Comment by stephanrauh** [comment]
Most examples come from this repository:  https://github.com/TheCoder4eu/BootsFaces-examples
The Tetris clone comes from https://github.com/stephanrauh/AngularTetrisOnBootsFaces.

**Comment by zhedar** [comment]
Seems like all broken links I found are fixed now, therefore I'm closing this.
