### ISSUE TITLE
maven build error

### ISSUE THREAD

**Issue by pavankd** [TheCoder4eu/BootsFacesWeb#22]
hi i am getting following error 
[ERROR] Failed to execute goal on project BootsFacesWeb: Could not resolve dependencies for project net.bootsfaces:BootsFacesWeb:war:0.8.5-SNAPSHOT: Could not find artifact net.bootsfaces:bootsfaces:jar:0.9.0-SNAPSHOT -> [Help 1]

**Comment by zhedar** [comment]
The current version of the showcase uses a Snapshot build of the [main project](https://github.com/TheCoder4eu/BootsFaces-OSP). You have to either build that yourself with `mvn clean install` or add the snapshot repo to the POM (see https://github.com/TheCoder4eu/BootsFaces-OSP/issues/369) or your maven settings.

**Comment by pavankd** [comment]
yaa got its working
