### ISSUE TITLE
BootsFaces tag decorator link

### ISSUE THREAD

**Issue by chongma** [TheCoder4eu/BootsFacesWeb#38]
on this page https://showcase.bootsfaces.net/RC1/miscellaneous/Configuration.jsf just below the heading `Activate the BootsFaces tag decorator` it says `...your JSF pages. This feature is described in detail here. To activate...`.  The link `here` does not go anywhere

**Comment by shafinmahmud** [comment]
actually it redirects to `http://127.0.0.1:8080/BootsFacesWeb/layout/div.jsf` !!!

**Comment by stephanrauh** [comment]
Now it should look better. BTW, the developer showcase is now at http://staging.bootsfaces.net/Showcase/
