### ISSUE TITLE
Images used on Carousel should be move to resources

### ISSUE THREAD

**Issue by ggam** [TheCoder4eu/BootsFacesWeb#40]
And loaded with the JSF resouce mechanism (<h:graphicImage/>)

**Comment by stephanrauh** [comment]
Why? What's the advantage of using the resource folder?

**Comment by ggam** [comment]
Just that we would show the JSF recommended way.

Don't know if there are any practical differences (maybe HTTP2 push? http://ridingthecrest.com/blog/2017/04/18/please-test-mojarra-2_3_1-with-server-push.html), but using <h:graphicImage /> would go through the JSF engine ("JSF Resource request", says the spec).

**Comment by stephanrauh** [comment]
Exactly. And sending images through the JSF engine is a lot slower than having the served fast by a caching Apache server (which is often in front of the application server).

I suggest we keep at least one "direct" demo while modifying the other demo. Thus, we test both approaches.

**Comment by ggam** [comment]
If caching is the only performance concern, can't it be solved directly by
the OmniFaces resourceHandler and by configuring the application server? Or
is the process itself so much slower?

**Comment by stephanrauh** [comment]
AFAIK Apache is written in Assembly language or C (at least the performance critical parts). Plus, it's a common pattern to put a firewall between Apache and Tomcat. So the JSF resource handler is two servers farther away from the web. I never managed to measure the performance difference reliably, but I've seen a huge difference in at least one project.

**Comment by ggam** [comment]
Interesting, I've never really thought about that.

I think we should leave there as it is, perhaps with a comment explaining
why we went that way.

After earching a little on the internet, seems like the only advantage of
using graphicImage is when having the images on the same war.

**Comment by stephanrauh** [comment]
IMHO, demonstrating both options is a good idea. As long as our showcase is our principal testing area, it's good to implement the same thing in different ways in order to detect regressions early.

**Comment by geopossachs** [comment]
work on this issue via commit 915c655106a27bfac72a95082ae4d2ea1b9e3ee1
