### ISSUE TITLE
b:selectBooleanCheckbox jsf markup 

### ISSUE THREAD

**Issue by chongma** [TheCoder4eu/BootsFacesWeb#42]
the JSF markup has disappeared from the checkbox page

**Comment by stephanrauh** [comment]
I can spot several errors in the checkbox page which have been solved since 1.1.0. But I fail to see where the JSF markup is missing. Can you elaborate, please?

TIA
Stephan

**Comment by chongma** [comment]
It was missing. It must have been temporary. Apologies
