### ISSUE TITLE
f:ajax does not update b:input text

### ISSUE THREAD

**Issue by mweiland** [TheCoder4eu/BootsFacesWeb#5]
when trying to update value of an input field with f:ajax i found

``` xml
<h:panelGrid columns="2">
             <h:outputText value="ID: "/>
             <b:inputText styleClass="tx-input-hours" id="inputID" value="#{testBean.id}" >
                <f:ajax event="keyup" render="inputName" execute="@this" />
           </b:inputText>
             <h:outputText value="Name: "/>
            <b:inputText styleClass="tx-input-hours" span="4" id="inputName" value="#{testBean.name}"/>
</h:panelGrid>
```

does not work, when you replace b:input text with h:input text, it works.

mojarra 2.2.11
bootsfaces 0.7.0

**Comment by mweiland** [comment]
how can i display html/xhtml code here ?

**Comment by stephanrauh** [comment]
Yes, we have yet to implement decent AJAX support. That seems to be on top of the communty's wish list for BootsFaces 0.8.

**Comment by stephanrauh** [comment]
As for editing: see https://guides.github.com/features/mastering-markdown/ (look for "syntax highlighting").

**Comment by stephanrauh** [comment]
I copied the content of the ticket to https://github.com/TheCoder4eu/BootsFaces-OSP/issues/134 and close this ticket.
