### ISSUE TITLE
Issue Commandbutton inside Datatable 

### ISSUE THREAD

**Issue by simoneobo** [TheCoder4eu/BootsFacesWeb#52]
Hello,

if you go to[ this page ](https://showcase.bootsfaces.net/forms/DataTable.jsf), section "Inputfields, command buttons and AJAX " and click to Edit button on a random line, but not the first one, insert a new number and press Enter to submit new value, the cell not update and the focus go on the first cell, everytime.

Is this a bug or is there a workaround to get it work?

Thank you

![cattura](https://user-images.githubusercontent.com/8329287/27230230-d4074540-52ae-11e7-9214-cb458c27541d.PNG)

**Comment by jepsar** [comment]
Please post issues with BootsFaces at https://github.com/TheCoder4eu/BootsFaces-OSP This repository is for the documentation.

**Comment by stephanrauh** [comment]
It's a bug. It seems I've committed the source code while debugging and forgot about it. It'll be fixed soon.
