### ISSUE TITLE
Links broken in componentSidebar.xhtml view

### ISSUE THREAD

**Issue by chsreedhar** [TheCoder4eu/BootsFacesWeb#54]
@stephanrauh 
Review below code to include context path, i.e., `http://showcase.bootsfaces.net` to all individual components under  Components navbar-sidebar in  componentSidebar.xhtml view

`<b:navLink href="#{componentListBean.addSlashIfNecessary(request.contextPath)}# componentListBean.url(c)}" value="#{componentListBean.getDisplayName(c)}" />`

**Comment by stephanrauh** [comment]
@chsreedhar That was quick :). Thanks!

The problem is that the bug only occurs in the root context. It worked well both on our test stage (http://www3.bootsfaces.net/Showcase/) and in my local Tomcat installation.

**Comment by stephanrauh** [comment]
@TheCoder4eu has solved it just a minute ago. Thanks!

**Comment by stephanrauh** [comment]
@chsreedhar If the problem still persists - or anything like it - don't hesitate to report it. Your help is appreciated!
