### ISSUE TITLE
setting javax.faces.SEPARATOR_CHAR to _ breaks things

### ISSUE THREAD

**Issue by sixcorners** [TheCoder4eu/BootsFacesWeb#6]
http://www.bootsfaces.net/integration/angularFaces.jsf
Generated jsf ids have underscores in them so they make for a bad separator character.

Also according to [this](https://stackoverflow.com/a/12619737) % isn't a valid character for an id.

**Comment by stephanrauh** [comment]
Thanks for pointing this out!

Former version of AngularFaces didn't cope with the standard JSF separator char (the colon). That's an annoying incompatibility between AngularJS, jQuery and JSF. It took me a while to learn how to deal with this. Nowadays, there's no need to modify the separator character. But you're right, I forgot to update the BootsFaces documentation.

**Comment by stephanrauh** [comment]
Done.
