### ISSUE TITLE
NPE in DateTimeBean

### ISSUE THREAD

**Issue by jepsar** [TheCoder4eu/BootsFacesWeb#60]
https://github.com/TheCoder4eu/BootsFacesWeb/blob/6908ecf8ab8c9a8594d33ada438f75d08065cd41/src/main/java/net/bootsfaces/demo/DateTimeBean.java#L225

Should be `.getResourceAsStream("META-INF/resources/bsf/js/moment.min.js");` (without leading slash).

**Comment by stephanrauh** [comment]
Which application server do you use?

On my machine, there's no NPE. But there's also no NPE after applying your suggestion, so I've committed the change.

**Comment by stephanrauh** [comment]
Please close the ticket if the bugfix, well, fixed the bug.

**Comment by jepsar** [comment]
Tested it with Payara Server 4.1.2.174 (build 192). I tested the change before I reported it :-)
