### ISSUE TITLE
Missing jsf code for live preview

### ISSUE THREAD

**Issue by ahofmeister** [TheCoder4eu/BootsFacesWeb#7]
As you can see on this page: http://www.bootsfaces.net/forms/commandButton.jsf  some jsf code is missing. 
1. Where is the disabled button? I really wish to see the code for that. 
2. a `<b:well`> is also missing.

**Comment by stephanrauh** [comment]
You can see the improved version in our CI showcase (http://www.bootsfaces.net/BootsFacesWeb/forms/commandButton.jsf).
