### ISSUE TITLE
Examples are not clear/complete enough

### ISSUE THREAD

**Issue by ahofmeister** [TheCoder4eu/BootsFacesWeb#9]
I'd lke to see fully, standalone examples. The user often  wants to copy and paste those examples and to see the magic happen. 

It might be useful for beginners with JSF and/or BootsFaces, so far. 

Example:

http://www.bootsfaces.net/forms/commandButton.jsf

In JSF markup, you can find `infoshow` in three dfiferent `update` attributes. Where is the component? It is missing. 

You might be thinking 'Oh well, it is  some sort of  a message component'. Well, you are right. But this is not the point in my opinion. Those examples have to be complete and fully standalone, with `<h:form>` and all necessary components.

**Comment by stephanrauh** [comment]
+1

Actually, we've started to improve the documentation several months ago. But we're still not where we want to be. Unfortunately, being familiar with BootsFaces we often don't see the weaknesses of our documentation, so we're very grateful for your hints. Thanks!

**Comment by ahofmeister** [comment]
Well, a good point is to start with creating a standalone example in a test application. If it does work nicely - someone other has to copy'n'paste this code and run it by himself. If it is also working fine, you can publish this example, I guess. It is not about, that your examples are wrong, they are just incomplete.

**Comment by stephanrauh** [comment]
I agree. The examples are meant to be copied and pasted, but that doesn't always work out yet.

In a way, it's difficult to provide truly isolated examples in the showcase. The showcase is a single application covering every component of BootsFaces. So every example is running on PrimeFaces, AngularFaces and OmniFaces, whether they need it or not. To overcome this problem, I've started to put a number of small examples in a separate repository (https://github.com/stephanrauh/BootsFaces-Examples). Each of these example focuses on a single feature of BootsFaces (and in some cases, of other frameworks). Maybe we should add links to these example project in the showcase.

**Comment by ahofmeister** [comment]
What do you mean with following sentence? 

> So every example is running on PrimeFaces, AngularFaces and OmniFaces, whether they need it or not.

This repo does look nice. There are a few good examples. I guess it is the right way to link those examples in the BootsFaces showcase. It may help, especially because there are only a few stackoverflow questions tagged with BootsFaces. 

I just saw `Examples` in the top right corner (http://www.bootsfaces.net/examples/index.jsf). It would be great to create more of those.

**Comment by stephanrauh** [comment]
It's a technical issue. We've included example for each of these frameworks. So they're part of the class path. That, in turn, activates certain parts of the frameworks, even if the current JSF page doesn't contain a widget of that framework. For instance, there's always the PrimePartialViewContext. In theory, this might change the behavior of the example.

**Comment by ahofmeister** [comment]
I guess, this is really only in theory. It should working, if you are not mixing PrimeFaces and BootsFaces components strangely.

**Comment by stephanrauh** [comment]
It was an issue in the case of AngularFaces, because AngularFaces adds several rapid prototyping features we had to switch off on most pages. BTW, how do you like this version of the documentation? http://www.bootsfaces.net/BootsFacesWeb/forms/commandButton.jsf

**Comment by ahofmeister** [comment]
Hm okay, I wonder, that PrimeFaces should make any problem. It does harm nicely. This example is much better!. Just a side note: You do not need `update="..."`, if the button is always disabled. :)

**Comment by stephanrauh** [comment]
You're right. I've also added an AJAX example to the demo. 
http://www.bootsfaces.net/BootsFacesWeb/forms/commandButton.jsf

**Comment by stephanrauh** [comment]
There's no such thing as perfect documentation... but I think we've come a long way. I close this issue, keeping the message in my mind.
